---


# List tapo devices
tapo:
    # Tapo devices require that you log in with the credentials
    # that you use to log into the app
    #
    user: ""
    passw: ""
    devices:
    
# List kasa devices
kasa:
    devices:
        - 
            name: "upstairs-fridge"
            ip: 192.168.1.50
        -
            name: "office-computers"
            ip: 192.168.1.51
        -
            name: "microwave"
            ip: 192.168.1.52
        -
            name: "coffee-station"
            ip: 192.168.1.53
        -
            name: "chest-freezer"
            ip: 192.168.1.54
        -
            name: "toaster-oven"
            ip: 192.168.1.55
        -
            name: "sump-pump"
            ip: 192.168.1.56
        -
            name: "washer"
            ip: 192.168.1.57
        -
            name: "camper"
            ip: 192.168.1.58

# InfluxDB outputs
influxdb:
    - 
        name: "local"
        host: "192.168.1.15"
        port: "8086"
        user: "root"
        password: "VDZLGRJz37sqyEirQDdUGmGy"
        database: "grafana"
        
