---


# List tapo devices
tapo:
    # Tapo devices require that you log in with the credentials
    # that you use to log into the app
    #
    user: ""
    passw: ""
    devices:
    
# List kasa devices
kasa:
    devices:
        - 
            name: "upstairs-fridge"
            ip: 192.168.1.50
        

# InfluxDB outputs
influxdb:
    - 
        name: "local"
        host: "192.168.1.15"
        port: "8086"
        user: "root"
        password: ""
        database: "testing_db"
        
